CI: rework compliance test
OpenAMP/open-amp pull request #225
Opened 2020-10-13 13:05 UTC by arnopo

The webispy/checkpatch-action does not seem to work properly.
Even if it detects codying style issue, the return state is successful.
this patch replace the action by the compliance python script obtained
from the Zephyr project.
This script also run gitlint to check commit messages.

Signed-off-by: Arnaud Pouliquen <arnaud.pouliquen@st.com>

2020-10-13 23:33 UTC, edmooring requested changes

2020-10-14 13:31 UTC, arnopo commented on .github/workflows/continuous-integration.yml
> +        git config --global user.name "Your Name"
it is a copy/past  from zephyr project (https://github.com/zephyrproject-rtos/zephyr/blob/master/.github/workflows/compliance.yml#L33)
As this is needed by the git rebase, i suggest to use same implementation than Zephyr

2020-10-14 22:16 UTC, edmooring commented on .github/workflows/continuous-integration.yml
> +        git config --global user.name "Your Name"
Okay.

2020-10-14 22:16 UTC, edmooring approved these changes

2020-10-15 09:41 UTC, arnopo commented on .github/workflows/continuous-integration.yml
>      - name: Run checkpatch review
webispy/checkpatch-action to suppress as replaced by compliance tests

2020-10-16 10:59 UTC, merged