Openamp bug fix on RPMSG_NS_DESTROY & rpmsg_send failed
OpenAMP/open-amp pull request #247
Opened 2020-12-03 07:39 UTC by GUIDINGLI

openamp: rpmsg_send() shouldn't check buffer size when get buffer failed
    
    cause _rpmsg_virtio_get_buffer_size() always return size > 0,
    when role is RPMSG_MASTER.

   openamp: fix ns_unbind_cb error when meet RPMSG_NS_DESTROY

2020-12-03 09:05 UTC, GUIDINGLI commented
@arnopo  Why the checks failed ?  This will check my Signed-off ?   What's the example?

2020-12-03 09:08 UTC, arnopo requested changes
LGTM , just need to update the commits messages

2020-12-03 09:17 UTC, arnopo commented
> @arnopo Why the checks failed ? This will check my Signed-off ? What's the example?

The compliance check is waiting a sign-of format with this format: First Last <email>.
So could you please provide your first name and last name in your signed-off-by?

2020-12-03 13:23 UTC, GUIDINGLI commented
> > @arnopo Why the checks failed ? This will check my Signed-off ? What's the example?
> 
> The compliance check is waiting a sign-of format with this format: First Last .
> So could you please provide your first name and last name in your signed-off-by?

done

2020-12-03 13:53 UTC, arnopo commented
Compliance check still fails because your git config is not pro pertly configured  you probably have something like that:
$ git config -l
...
user.name=ligd
...
should be  user.name=Guiding Li

it Ok for this time but i would suggest to change this for future commits. This compliance test is use in several open source project.

2020-12-03 13:53 UTC, arnopo approved these changes

2020-12-04 03:03 UTC, GUIDINGLI commented
> Compliance check still fails because your git config is not pro pertly configured you probably have something like that:
> $ git config -l
> ...
> user.name=ligd
> ...
> should be user.name=Guiding Li
> 
> it Ok for this time but i would suggest to change this for future commits. This compliance test is use in several open source project.

This check is not reasonable I think.
If someone in some country don't have divided on  lastname firstname. 
Or if someone just have one short English name, like Mike David Lucy ...
What will he/she do ?

2020-12-04 08:31 UTC, arnopo commented
> This check is not reasonable I think.
This check is mainly to encourage contributor to use their real name and not a pseudo or anonymous contribution.
It is a good practice that help to identify the contributor of a patch.
If you have a look to some other opensource projects ( such as Linux or Zephy), you will find this kind of check mainly based on gitlint tool.

> If someone in some country don't have divided on lastname firstname.
> Or if someone just have one short English name, like Mike David Lucy ...
> What will he/she do ?
If we face the case we will just discuss together to find the best solution. At the end having this check fails does not mean that we do not accept the commit.

2020-12-09 03:43 UTC, edmooring approved these changes
Looks good to me.

2020-12-10 15:23 UTC, merged