Virtio exp
OpenAMP/open-amp pull request #397
Opened 2022-05-25 16:59 UTC by danmilea

virtio-mmio framework for lib open-amp

2022-05-25 17:46 UTC, xiaoxiang781216 commented on lib/include/openamp/virtio.h
> +#define VIRTIO_CONFIG_FEATURES_OK 0x08
align 0x08 with other line

2022-05-25 17:46 UTC, xiaoxiang781216 commented on lib/include/openamp/virtqueue.h
> +				     uint32_t *len);
aglin uint32_t to struct at line 194

2022-05-25 17:46 UTC, xiaoxiang781216 commented on lib/virtio/virtqueue.c
> +uint16_t virtqueue_buffer_writable(struct virtqueue *vq, uint16_t avail_idx)
should we use bool instead uint16_t

2022-05-25 17:46 UTC, xiaoxiang781216 commented on lib/include/openamp/virtio.h
> +#define VIRTIO_F_ACCESS_PLATFORM	33
align 33 with 32 at line 93

2022-05-25 17:46 UTC, xiaoxiang781216 commented on lib/include/openamp/virtio.h
> +#define VIRTIO_F_ACCESS_PLATFORM	33
should we use VIRTIO_ACCESS_F_PLATFORM

2022-05-25 17:46 UTC, xiaoxiang781216 commented on lib/include/openamp/virtio.h
> +#define VIRTIO_F_RING_PACKED		34
same comment as VIRTIO_F_ACCESS_PLATFORM

2022-05-25 17:46 UTC, xiaoxiang781216 commented on lib/virtio_mmio/virtio_mmio_queue.c
> +void virtqueue_init(const struct device *dev, unsigned int idx, struct virtqueue *vq, void (*cb)(void*), void *cb_arg)
remove the unused code

2022-05-25 17:46 UTC, xiaoxiang781216 commented on lib/virtio_mmio/virtio_mmio_queue.c
> +void *virtqueue_dequeue_buf(struct virtqueue *vq, uint32_t *len)
remove too

2022-05-25 17:46 UTC, xiaoxiang781216 commented on lib/include/openamp/virtio_config.h
> + * Virtio platform device driver
why name the file virtio_config.h, but all macros are related to virtio_mmio.h

2022-06-02 10:28 UTC, arnopo reviewed
Hi @danmilea 

Quite a lot of comment... I reviewed considering that i could be applied on main branch.

That said  this branch has been created first as a experimental branch, to initiate virtio evolution based on your demo and @vingu-linaro work.
So I could integrate it like this for a demo need.

Now It depends how we would like to proceed for a collaborative work.
It will be necessary at a time to clean the code and make it compliant with the checkpatch...

2022-06-02 10:29 UTC, arnopo commented on lib/include/openamp/virtio.h
> +#define VIRTIO_F_VERSION_1 32
to move after VIRTIO_TRANSPORT_F_END declaration

2022-06-02 13:44 UTC, danmilea commented on lib/include/openamp/virtio.h
> +#define VIRTIO_ID_SCMI       0x20UL
The actual ID in decimal is 32, which matches the SCMI device ID in https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.html#x1-2160005

2022-06-08 09:28 UTC, arnopo commented on scripts/checkpatch.pl
> +						"Alignment should match open parenthesis newindent = " . "$newindent" . "gt =  " . "$goodtabindent" . "gs = " . "$goodspaceindent" . "\n" . $hereprev) &&
to add checkpatch fix in a separate patch (also on main branch if it fix an issue)

2022-06-08 15:36 UTC, arnopo reviewed
Few new comments for my second round

2022-06-08 15:36 UTC, arnopo commented on lib/include/openamp/virtio_mmio.h
> +#define MAGIC_VALUE ('v' | ('i' << 8) | ('r' << 16) | ('t' << 24))
definitions, variables, structures and function that are exported should be prefixed by `virtio_mmio`

2022-06-08 15:36 UTC, arnopo commented on lib/include/openamp/virtio_mmio.h
> +}
these functions above related to the virtio_device struct could be moved in virtio.h ( and some other below)

2022-06-08 15:36 UTC, arnopo commented on lib/include/openamp/virtio_mmio.h
> +inline void virtqueue_notify(struct virtqueue *vq)
what about using `virtqueue_kick` instead?

2022-06-08 15:36 UTC, arnopo commented on lib/virtio_mmio/virtio_mmio.c
> +	virtio_mmio_write32(vq->vq_dev, VIRTIO_MMIO_QUEUE_NOTIFY, vq->vq_queue_index);
Add a comment here specifying that the VIRTIO_F_NOTIFICATION_DATA feature is not supported.
could be nice to return an error also in _virtio_mmio_set_features

2022-06-08 15:36 UTC, arnopo commented on lib/include/openamp/virtio_mmio.h
> +void *virtqueue_dequeue(struct virtqueue *vq, uint32_t *len);
I waiting to see how these 3 functions will evolve... waiting that could you create a virtio_mmio_queue.h for them?

2022-06-08 15:36 UTC, arnopo commented on lib/include/openamp/virtio_mmio.h
> +
The 2 functions above could be moved in virtqueue.h

2022-06-16 16:40 UTC, arnopo requested changes
A potential deadlock to fix. Then ok for me to merge it in the virtio_exp branch
@edmooring : do you want to review it before I merge?  At the end a new round of review will be performed when merging in the main branch...

2022-06-16 16:40 UTC, arnopo commented on lib/virtio/virtqueue.c
> +		return NULL;
`VQUEUE_IDLE(vq); ` missing before return

2022-06-17 16:10 UTC, arnopo commented on lib/virtio/virtqueue.c
> +	flags = vq->vq_ring.desc[*avail_idx].flags;
As we access to the vring here i would prefer to to keep `VQUEUE_BUSY` protection... you can use a goto if you want to have a single call to  `VQUEUE_IDLE()` in  he function

2022-06-20 07:13 UTC, arnopo approved these changes

2022-06-24 13:42 UTC, merged