BUGFIX: change unsuitable atomic_int to atomic_flag
OpenAMP/open-amp pull request #472
Opened 2023-03-01 02:14 UTC by mzyx-hnu

This patch tries to fix issue#471

2023-03-03 13:42 UTC, arnopo requested changes
The fix seems valid to me. I wonder if we need to have a `atomic_flag_test_and_set` on init,  but that seems inline with the initial value set by `atomic_init`...

One cosmetic remark:
Please, split in 2 commits: one for the lib one` for the app. have look to existing commit to see commit subjet prefix to use

2023-03-03 13:42 UTC, arnopo commented on apps/examples/linux_rpc_demo/linux_rpc_demo.c
> +	atomic_flag_test_and_set(&wait_resp);
I would expect here  &wait_resp = ATOMIC_FLAG_INIT 
```
wait_resp = (atomic_flag)ATOMIC_FLAG_INIT;
atomic_flag_test_and_set(&wait_resp)
```

2023-03-03 13:42 UTC, arnopo commented on lib/proxy/rpmsg_retarget.c
> +	atomic_flag_test_and_set(&rpc->nacked);
same here

2023-03-04 06:16 UTC, edmooring reviewed
Not much to say here. I think this will be good to go with @arnopo comments addressed.

2023-03-06 08:28 UTC, mzyx-hnu commented
> The fix seems valid to me. I wonder if we need to have a `atomic_flag_test_and_set` on init, but that seems inline with the initial value set by `atomic_init`...
> 
> One cosmetic remark: Please, split in 2 commits: one for the lib one` for the app. have look to existing commit to see commit subjet prefix to use

updated as the above comments

2023-03-07 10:35 UTC, arnopo approved these changes

2023-03-09 23:31 UTC, edmooring approved these changes
Good to go.

2023-03-14 18:00 UTC, merged