rpmsg_virtio.c: virtqueue_kick after all rx buffer release
OpenAMP/open-amp pull request #615
Opened 2024-09-19 09:16 UTC by wyr-7

virtqueue_kick after all rx buffer release to improve performance

2024-09-20 13:50 UTC, arnopo reviewed
I'm not convinced that this is an improvement in terms of performance. For some use cases, yes; for others, no. 

* In the current implementation, each time we free a buffer, we notify the other side.

  Pros:
  - If the other side is waiting for a free buffer, it does not have to wait for the local side to process all the buffers.

  Cons:
  - One notification per buffer.

* With your PR, there is only one notification when the RX queue is empty.

  Pros:
  - Decreases the number of IRQs on the other side.

  Cons:
  - If the remote side is waiting for a free buffer, it has to wait until all buffers are processed. This is not compatible with some real-time use cases, such as audio streaming.
  -  **my main concern:** It seems that your proposal is not compliant with the VIRTIO protocol, so it cannot be the default behavior. 

Have you tried using VIRTIO_F_EVENT_IDX?

2024-09-23 11:36 UTC, CV-Bowen commented
@arnopo Hi, about your concerns:

>   * If the remote side is waiting for a free buffer, it has to wait until all buffers are processed. This is not compatible with some real-time use cases, such as audio streaming.

The rpmsg virtio default implementation in OpenAMP use polling method to wait the tx buffer, so in this case, the real-time performance is not affected and the number of interrupts are reduced.

But if we implemented the `notify_wait_cb` in `struct rpmsg_virtio_device` and make the tx buffer wait method from polling mode to event mode, things would be different and the real-time performance is indeed affected (Only when the buffers is not enough), and also the interrupts number are increased.

Is the default behavior more important?

>   * **my main concern:** It seems that your proposal is not compliant with the VIRTIO protocol, so it cannot be the default behavior.

As you said, this behavior indeed does not conform to the VIRTIO standard, the virtio standard says:
- VirtIO Device --> VirtIO Driver: the device side must send a notification if writes a descriptor index into the used ring (see 2.7.7.2 Device Requirements: Used Buffer Notification Suppression)
- VirtIO Driver --> VirtIO Device: the driver side must send a notification if writes a descriptor index into the available ring (see 2.7.10.1 Driver Requirements: Available Buffer Notification Suppression).

But actually, Linux does the same thing like this PR, please see: https://github.com/torvalds/linux/blob/master/drivers/rpmsg/virtio_rpmsg_bus.c#L778
```c
static void rpmsg_recv_done(struct virtqueue *rvq)
{
	struct virtproc_info *vrp = rvq->vdev->priv;
	struct device *dev = &rvq->vdev->dev;
	struct rpmsg_hdr *msg;
	unsigned int len, msgs_received = 0;
	int err;

	msg = virtqueue_get_buf(rvq, &len);
	if (!msg) {
		dev_err(dev, "uhm, incoming signal, but no used buffer ?\n");
		return;
	}

	while (msg) {
		err = rpmsg_recv_single(vrp, dev, msg, len);
		if (err)
			break;

		msgs_received++;

		msg = virtqueue_get_buf(rvq, &len);
	}

	dev_dbg(dev, "Received %u messages\n", msgs_received);

	/* tell the remote processor we added another available rx buffer */
	if (msgs_received)
		virtqueue_kick(vrp->rvq);
}
```

2024-09-26 16:29 UTC, arnopo commented
> @arnopo Hi, about your concerns:
> 
> > * If the remote side is waiting for a free buffer, it has to wait until all buffers are processed. This is not compatible with some real-time use cases, such as audio streaming.
> 
> The rpmsg virtio default implementation in OpenAMP use polling method to wait the tx buffer, so in this case, the real-time performance is not affected and the number of interrupts are reduced.
> 
> But if we implemented the `notify_wait_cb` in `struct rpmsg_virtio_device` and make the tx buffer wait method from polling mode to event mode, things would be different and the real-time performance is indeed affected (Only when the buffers is not enough), and also the interrupts number are increased.
> 
> Is the default behavior more important?

Yes, it is, as it can affect existing projects. If we want to maintain the stability of the library, we have to take legacy into account.

> 
> > * **my main concern:** It seems that your proposal is not compliant with the VIRTIO protocol, so it cannot be the default behavior.
> 
> As you said, this behavior indeed does not conform to the VIRTIO standard, the virtio standard says:
> 
> * VirtIO Device --> VirtIO Driver: the device side must send a notification if writes a descriptor index into the used ring (see 2.7.7.2 Device Requirements: Used Buffer Notification Suppression)
> * VirtIO Driver --> VirtIO Device: the driver side must send a notification if writes a descriptor index into the available ring (see 2.7.10.1 Driver Requirements: Available Buffer Notification Suppression).
> 
> But actually, Linux does the same thing like this PR, please see: https://github.com/torvalds/linux/blob/master/drivers/rpmsg/virtio_rpmsg_bus.c#L778
> 
> ```c
> static void rpmsg_recv_done(struct virtqueue *rvq)
> {
> 	struct virtproc_info *vrp = rvq->vdev->priv;
> 	struct device *dev = &rvq->vdev->dev;
> 	struct rpmsg_hdr *msg;
> 	unsigned int len, msgs_received = 0;
> 	int err;
> 
> 	msg = virtqueue_get_buf(rvq, &len);
> 	if (!msg) {
> 		dev_err(dev, "uhm, incoming signal, but no used buffer ?\n");
> 		return;
> 	}
> 
> 	while (msg) {
> 		err = rpmsg_recv_single(vrp, dev, msg, len);
> 		if (err)
> 			break;
> 
> 		msgs_received++;
> 
> 		msg = virtqueue_get_buf(rvq, &len);
> 	}
> 
> 	dev_dbg(dev, "Received %u messages\n", msgs_received);
> 
> 	/* tell the remote processor we added another available rx buffer */
> 	if (msgs_received)
> 		virtqueue_kick(vrp->rvq);
> }
> ```
rproc virtio/rpmsg virtio in Linux is probably not the best example in terms of virtio specification conformance. :smiley:

That said, your proposal is still valid in terms of optimization. However, I would be in favor of supporting both, even if it would add a new build configuration to test.

@edmooring @tnmysh, any opinions on that?

2024-09-27 07:15 UTC, CV-Bowen commented
> rproc virtio/rpmsg virtio in Linux is probably not the best example in terms of virtio specification conformance.

Yes, kick only one time when we need add serveral buffers to the virtqueue is a very easy way to optimize the performance and I found more virtio drivers' implementations in linux do this thing:

virtio_net: https://github.com/torvalds/linux/blob/master/drivers/net/virtio_net.c#L3053
vsock_virtio: https://github.com/torvalds/linux/blob/master/net/vmw_vsock/virtio_transport.c#L155

@arnopo So what's your plan about this? If it's OK, you could give us some advices so that we can continue this PR.

CC @edmooring @tnmysh

2024-09-30 05:44 UTC, edmooring reviewed
I agree with @arnopo at least in part. If we do support this, it should be in addition to the current approach, and it should not be the default. Current users of the library will be surprised if the default behavior changes. 

This might be an optimization for performance in some applications, but it might also be a pessimization (the opposite of optimization) for others because it could affect latency.

2024-09-30 07:01 UTC, arnopo commented
> > rproc virtio/rpmsg virtio in Linux is probably not the best example in terms of virtio specification conformance.
> 
> Yes, kick only one time when we need add serveral buffers to the virtqueue is a very easy way to optimize the performance and I found more virtio drivers' implementations in linux do this thing:
> 
> virtio_net: https://github.com/torvalds/linux/blob/master/drivers/net/virtio_net.c#L3053 vsock_virtio: https://github.com/torvalds/linux/blob/master/net/vmw_vsock/virtio_transport.c#L155
> 
> @arnopo So what's your plan about this? If it's OK, you could give us some advices so that we can continue this PR.
> 
> CC @edmooring @tnmysh

Concerning the implementation, one way to do it could be to define an RPMSG_VIRTIO_ENABLED macro similar to VIRTIO_ENABLED and a VQ_RX_EMPTY_NOTIFY build config. Then, use if (RPMSG_VIRTIO_ENABLED(VQ_RX_EMPTY_NOTIFY)) to define the behavior.

```c
if (RPMSG_VIRTIO_ENABLED(VQ_RX_EMPTY_NOTIFY))
   /* only notify when no more Message in queue */
else
  /*  notify for each buffer released */
```

2024-10-04 15:13 UTC, CV-Bowen commented
@arnopo @edmooring Thanks for the reply and we will update this PR based on your suggestions @arnopo.

2024-10-08 09:01 UTC, wyr-7 commented
> Concerning the implementation, one way to do it could be to define an RPMSG_VIRTIO_ENABLED macro similar to VIRTIO_ENABLED and a VQ_RX_EMPTY_NOTIFY build config. Then, use if (RPMSG_VIRTIO_ENABLED(VQ_RX_EMPTY_NOTIFY)) to define the behavior.
> 
> ```c
> if (RPMSG_VIRTIO_ENABLED(VQ_RX_EMPTY_NOTIFY))
>    /* only notify when no more Message in queue */
> else
>   /*  notify for each buffer released */
> ```

rpmsg_virtio.c already have use VIRTIO_ENABLED，so can we use VIRTIO_ENABLED directly?

2024-10-08 11:25 UTC, wyr-7 commented on lib/rpmsg/rpmsg_virtio.c
> +				virtqueue_kick(rvdev->rvq);
Ok, done.

2024-10-09 07:07 UTC, arnopo commented on cmake/options.cmake
> +if (NOT WITH_VQ_RX_EMPTY_NOTIFY)
pease document `WITH_VQ_RX_EMPTY_NOTIFY` in README.md

2024-10-09 08:17 UTC, arnopo requested changes

2024-10-09 08:17 UTC, arnopo commented on lib/rpmsg/rpmsg_virtio.c
> +			release = true;
add a  comment  such as:
/* kick will be sent only when last buffer is released */

2024-10-10 09:00 UTC, arnopo requested changes
implementation seems LGTM,  few typos to fix. 

Please also fix commit message, here is a proposal:

**rpmsg: Allow to send virtqueue_kick only when RX queue is empty** 

**A**dd VQ_RX_EMPTY_NOTIFY config to define the behavior. If
VQ_RX_EMPTY_NOTIFY is disabled, notify the other side each
time a buffer is released. **If VQ_RX_EMPTY_NOTIFY is enabled,
only send one notification** when the RX queue is empty to
improve performanc**e.**

2024-10-11 03:07 UTC, wyr-7 commented
> impementation seemms LGTM, few typos to fix.
> 
> Please also fix commit message, here is a proposal:
> 
> **rpmsg: Allow to send virtqueue_kick only when RX queue is empty**
> 
> **A**dd VQ_RX_EMPTY_NOTIFY config to define the behavior. If VQ_RX_EMPTY_NOTIFY is disabled, notify the other side each time a buffer is released. **If VQ_RX_EMPTY_NOTIFY is enabled, only send one notification** when the RX queue is empty to improve performanc**e.**

Thanks for pointing out the grammatical error, done.

2024-10-11 09:57 UTC, arnopo approved these changes

2024-10-17 06:56 UTC, edmooring approved these changes
Looks good to go.

2024-10-17 13:59 UTC, merged