Update CI
OpenAMP/open-amp pull request #619
Opened 2024-09-23 15:16 UTC by arnopo

Update CI to build the https://github.com/OpenAMP/openamp-system-reference/tree/main/examples/legacy_apps applications instead of the https://github.com/OpenAMP/open-amp/tree/main/apps applications, which will be deprecated in the next release.

2024-10-11 19:23 UTC, tnmysh approved these changes
Looks good to me.

2024-10-16 15:01 UTC, wmamills requested changes
In general looks good, some nits you should fix.
And then decide to tackle the dir structure or not

2024-10-16 15:01 UTC, wmamills commented on .github/workflows/continuous-integration.yml
> +      uses: actions/checkout@v4
"path: open-amp" HERE ???
with adjustments in script?

I think libmetal and openamp-system-reference are sub directories of open-amp.  That works but is a little strange.  Is this easy to fix as described above??  If not we will deal with it later.

2024-10-16 15:11 UTC, wmamills commented on .github/workflows/continuous-integration.yml
> +      uses: actions/checkout@v4
I take this comment back.  Every build would need to be updated not just the linux build.
We should do this in another PR

2024-10-17 17:22 UTC, wmamills approved these changes
I reviewed this and tested it as well.
I think it is ready.

2024-10-18 07:15 UTC, merged